---
# App owners would either need to chown the entire agent folder to their app's user OR grant their app's user read/write access to the agent folder
- name: Get a VPC info by name
  amazon.aws.ec2_vpc_net_info:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ aws_vpc_name }}"
  register: aws_vpc_info
