- name: Get security group info
  amazon.aws.ec2_group_info:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_region: "{{ aws_region }}"
    filters:
      group-name: "{{ aws_networking_name }}-SecurityGroup"
      vpc-id: "{{ item.vpc_id | default(vpc_id) }}"
  register: aws_security_group_info