---
# App owners would either need to chown the entire agent folder to their app's user OR grant their app's user read/write access to the agent folder
# https://docs.ansible.com/ansible/latest/collections/community/aws/aws_secret_module.html
- name: Add string to AWS Secrets Manager
  community.aws.aws_secret:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_region: "{{ aws_region }}"
    name: "{{ aws_secret_name }}"
    state: present
    secret_type: 'string'
    secret: "{{ aws_secret_value }}"
  when: create_secret == true
  register: aws_secret

- name: remove string from AWS Secrets Manager
  community.aws.aws_secret:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_region: "{{ aws_region }}"
    name: "{{ aws_secret_name }}"
    state: absent
    secret_type: 'string'
    secret: "{{ aws_secret_value }}"
  when: remove_secret == true
