---
# tasks file for secrets
- include_tasks: aws_secrets.yml
  when: create_secret == true or remove_secret == true

- name: Print secret info
  debug:
    msg: "The secret created is '{{ aws_secret.secret.arn }}'"
  when: create_secret == true 