### REQUIRED
namespace: appdynamics

name: aws

version: "21.2.0" 

readme: README.md

authors:
- Aleksandra Jovovic

description: Install and Configure AppDynamics agents in AWS environments

license_file: 'LICENSE'

tags: 
  - monitoring
  - apm
  - performance
  - agent
  - appdynamics
  - cloud
  - aws
  - ecs
  - fargate
  
# Collections that this collection requires to be installed for it to be usable.
dependencies: 
  amazon.aws: '>=1.4.0'
  community.aws: '>=1.4.0'

repository: https://github.com/Appdynamics/appdynamics-ansible-ecs-fargate.git

documentation: https://github.com/Appdynamics/appdynamics-ansible-ecs-fargate.git

homepage: https://github.com/Appdynamics/appdynamics-ansible-ecs-fargate.git

issues: https://github.com/Appdynamics/appdynamics-ansible-ecs-fargate.git/issues

build_ignore: 
  - build 
  - '*.tar.gz'
  - 'install_collection.sh'
  - '.github'
  - 'docs/*.gif'
  - 'ansible.cfg'
  - 'inventory/*'
  - '.local.*'
  - 'changelogs/*'
  - 'CONTRIBUTING.md'


