- name: Get task definition info
  community.aws.ecs_taskdefinition_info:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_region: "{{ aws_region }}"
    task_definition: "{{ task_definition_name }}"
  register: aws_task_definition_info