---
- hosts: all
  tasks:
    - name: Include variables for the controller settings
      include_vars: vars/.local.controller.yml

    - name: Include variables for the agent settings
      include_vars: vars/.local.agent.yml

    - name: Include cloud provider settings
      include_vars: vars/.local.cloud-provider.yml

    - name: Ensure botocore and boto3 modules are installed
      pip:
        name: [ "boto3", "botocore"]
        extra_args: "--user"

    - include_role:
        name: secrets
      vars:
        create_secret: true
        remove_secret: false
        aws_secret_name: test-secret-name
        aws_secret_value: "{{ controller_account_access_key }}"

    - include_role:
        name: logs
      vars:
        create_log_group: true
        remove_log_group: false
        log_group_name: /ecs/test-cluster-ansible

    - include_role:
        name: identity
      vars:
        create_policies: true
        remove_policies: false
        aws_iam_name: my-task

    - include_role:
        name: networking
      vars:
        create_vpc: true
        remove_vpc: false
        aws_vpc_name: "VPC for AppDynamics"
        aws_vpc_cidr_block: 10.10.0.0/16
        application_port: 8080
        aws_networking_name: my-task

    - include_role:
        name: aws_ecs
      vars:
        create_cluster: true
        remove_cluster: false
        ecs_cluster_name: test-ansible-cluster

        create_task_definition: true
        remove_task_definition: false
        task_definition_name: my-task
        application_type: java # java | dotnet | node
        application_image: sashaz/java-services:v5
        agent_image: appdynamics/java-agent:20.8.0

        create_ecs_service: true
        remove_ecs_service: false