---
- hosts: all
  tasks:
    - name: Include variables for the controller settings
      include_vars: vars/.local.controller.yml

    - name: Include variables for the agent settings
      include_vars: vars/.local.agent.yml

    - name: Include variables for the monitored application settings
      include_vars: vars/.local.application.yml

    - name: Include cloud provider settings
      include_vars: vars/.local.cloud-provider.yml

    - name: Ensure botocore and boto3 modules are installed
      pip:
        name: [ "boto3", "botocore"]
        extra_args: "--user"

    - include_role:
        name: aws_ecs
      vars:
        create_cluster: false
        remove_cluster: true
        ecs_cluster_name: "{{ aws_ecs_cluster_name }}"

        create_task_definition: false
        remove_task_definition: true
        task_definition_name: "{{ aws_task_definition_name }}"
        application_type: "{{ application_type_value }}"
        application_image: "{{ application_image_value }}"
        agent_image: "{{ appd_agent_image }}"

        create_ecs_service: false
        remove_ecs_service: true
    
    - include_role:
        name: networking
      vars:
        create_vpc: false
        remove_vpc: true
        aws_vpc_name: "{{ aws_vpc_name_tag }}"
        aws_vpc_cidr_block: "{{ aws_vpc_cidr_block_value }}"
        aws_networking_name: "{{ aws_task_definition_name }}"

    - include_role:
        name: identity
      vars:
        create_policies: false
        remove_policies: true
        aws_iam_name: "{{ aws_task_definition_name }}"

    - include_role:
        name: secrets 
      vars:
        create_secret: false
        remove_secret: true
        aws_secret_name: "{{ aws_controller_secret_name }}"

    - include_role:
        name: logs
      vars:
        create_log_group: false
        remove_log_group: true
        log_group_name: "{{ aws_log_group_name }}"
    